spring.application.name=ecom-proj

spring.datasource.url=jdbc:postgresql://localhost:5432/your_db_name
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.username=postgres
spring.datasource.password=your_password

spring.jpa.defer-datasource-initialization=true

